runtime: python  # Choose your desired Python version
env: flex
entrypoint: gunicorn -b :$PORT main:app
instance_class: F1


runtime_config:
    operating_system: "ubuntu18"
    runtime_version: "3.9"

env_variables:

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

# Include any additional files or folders you need to deploy
